version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "marvel-characters"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hnxkfbkczf4f"
s3_prefix = "marvel-characters"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["MarvelCharactersNextFunction=095138843627.dkr.ecr.us-west-2.amazonaws.com/marvelcharacters04b4a9a6/marvelcharactersnextfunctione1cf85b5repo"]