version = 0.1

[main.build.parameters]
template_file="./template.yaml"
manifest="package.json"

[main.deploy.parameters]
profile="default"
region="us-west-2"
stack_name = "marvel-characters-sam"
s3_bucket = "marvel-characters-sam"
s3_prefix = "main"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repository = "095138843627.dkr.ecr.us-west-2.amazonaws.com/marvel-characters-sam"
