AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Marvel Characters Next Project

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Resources:
  MarvelCharactersNextApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Marvel-Characters-Api
      Description: API for Marvel Characters
      StageName: main
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - '*'

  MarvelCharactersNextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          NODE_ENV: production
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId:
              Ref: MarvelCharactersNextApi
            Path: /
            Method: ANY

        ProxyPlus:
          Type: Api
          Properties:
            RestApiId:
              Ref: MarvelCharactersNextApi
            Path: /{proxy+}
            Method: ANY

    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MarvelCharactersNextApi:
    Description: 'API Gateway endpoint URL for Prod stage for Marvel Characters Next function'
    Value: !Sub 'https://${MarvelCharactersNextApi}.execute-api.${AWS::Region}.amazonaws.com/main'
  MarvelCharactersNextFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt MarvelCharactersNextFunction.Arn
  MarvelCharactersNextFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt MarvelCharactersNextFunctionRole.Arn
