AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs18.x

  SAM Template for Marvel-Characters-Next

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Resources:
  MarvelCharactersNextApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Marvel-Characters-Api
      Description: API for Marvel Characters
      StageName: Prod
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - '*/*'

  MarvelCharactersNextFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ProxyRootApi:
          Type: Api
          Properties:
            RestApiId: !Ref MarvelCharactersNextApi
            Path: /
            Method: any
        ProxyPlusApi:
          Type: Api
          Properties:
            RestApiId: !Ref MarvelCharactersNextApi
            Path: /{proxy+}
            Method: any
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./marvel-characters
      Dockerfile: Dockerfile

  MyApiMapping:
    Type: 'AWS::ApiGatewayV2::ApiMapping'
    DependsOn:
      - MarvelCharactersNextApi
      - MarvelCharactersNextFunction
      - LambdaApiGatewayExecutionPermission
    Properties:
      DomainName: marvel-characters.link
      ApiId: !Ref MarvelCharactersNextApi
      Stage: Prod
      ApiMappingKey: main

  LambdaApiGatewayExecutionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName: !GetAtt MarvelCharactersNextFunction.Arn
    Principal: apigateway.amazonaws.com
    SourceArn: !Join
      - ''
      - - 'arn:aws:execute-api:'
        - !Ref AWS::Region
        - ':'
        - !Ref AWS::AccountId
        - ':'
        - !Ref MarvelCharactersNextApi
        - '/*/*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MarvelCharactersNextApi:
    Description: 'API Gateway endpoint URL for Prod stage for Marvel Characters Next function'
    Value: !Sub 'https://${MarvelCharactersNextApi}.execute-api.${AWS::Region}.amazonaws.com/main'
  MarvelCharactersNextFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt MarvelCharactersNextFunction.Arn
  MarvelCharactersNextFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt MarvelCharactersNextFunctionRole.Arn
